# Site settings
title: "Mili's Blog"
email: "milaad.farzian@gmail.com"
description: >-
  Notes, experiments, and projects by milad Farzian — 
  a 23-year-old backend developer exploring Python, Django, FastAPI, Redis, 
  and building side projects with Cloudflare, Telegram, and beyond.
twitter_username: ""
github_username: MiliScripts
linkedin_username: "miladfarzian"
minimal_mistakes_skin: default
search: true

url: "https://blog.imili.ir"
baseurl: ""

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: Asia/Tehran

include:
  - _pages

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "milad Farzian"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Backend developer (Python/FastAPI/Django). I build tools, blogs, bots, and experiments — learning in public."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://blog.imili.ir"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/MiliScripts"
    - label: "GitHub (alt)"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/MiliScripts"
    - label: "Telegram"
      icon: "fab fa-fw fa-telegram"
      url: "https://t.me/milifarzian"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/milifarzian"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/MiliScripts``"
    - label: "Telegram"
      icon: "fab fa-fw fa-telegram"
      url: "https://t.me/milifarzian"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/milifarzian"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

future: true